In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
#create csvs into dataframes

flight_file = "Kaggle2016_flight_data.csv"
flight_df = pd.read_csv(flight_file)
flight_df.head()

,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,UNIQUE_CARRIER,FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,...,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,Unnamed: 42
0,1,1,3,7,2016-01-03,F9,694,11292,1129202,30325,...,87.0,1.0,692.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,3,7,2016-01-03,F9,809,14027,1402702,34027,...,224.0,1.0,1679.0,19.0,0.0,0.0,0.0,0.0,NaN,NaN
2,1,1,3,7,2016-01-03,F9,907,15356,1535602,35356,...,60.0,1.0,373.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,3,7,2016-01-03,F9,908,14492,1449202,34492,...,57.0,1.0,373.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1,3,7,2016-01-03,F9,915,15356,1535602,35356,...,107.0,1.0,693.0,2.0,0.0,18.0,0.0,0.0,NaN,NaN

In [10]:
#use pandas to read data
flight_file_pd = pd.read_csv(flight_file)
flight_file_pd.head()

,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_DATE,UNIQUE_CARRIER,FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,...,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,Unnamed: 42
0,1,1,3,7,2016-01-03,F9,694,11292,1129202,30325,...,87.0,1.0,692.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1,3,7,2016-01-03,F9,809,14027,1402702,34027,...,224.0,1.0,1679.0,19.0,0.0,0.0,0.0,0.0,NaN,NaN
2,1,1,3,7,2016-01-03,F9,907,15356,1535602,35356,...,60.0,1.0,373.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,3,7,2016-01-03,F9,908,14492,1449202,34492,...,57.0,1.0,373.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,1,3,7,2016-01-03,F9,915,15356,1535602,35356,...,107.0,1.0,693.0,2.0,0.0,18.0,0.0,0.0,NaN,NaN

In [11]:
#display a statistical overview of the DataFrame 
flight_file_pd.describe()

,QUARTER,MONTH,DAY_OF_MONTH,DAY_OF_WEEK,FL_NUM,ORIGIN_AIRPORT_ID,ORIGIN_AIRPORT_SEQ_ID,ORIGIN_CITY_MARKET_ID,DEST_AIRPORT_ID,DEST_AIRPORT_SEQ_ID,...,AIR_TIME,FLIGHTS,DISTANCE,CARRIER_DELAY,WEATHER_DELAY,NAS_DELAY,SECURITY_DELAY,LATE_AIRCRAFT_DELAY,FIRST_DEP_TIME,Unnamed: 42
count,1.856061e+06,1.856061e+06,1.856061e+06,1.856061e+06,1.856061e+06,1.856061e+06,1.856061e+06,1.856061e+06,1.856061e+06,1.856061e+06,...,1.824403e+06,1856061.0,1.856061e+06,336767.000000,336767.000000,336767.000000,336767.000000,336767.000000,11333.000000,0.0
mean,3.010901e+00,8.040850e+00,1.581386e+01,3.923485e+00,2.106785e+03,1.268670e+04,1.268673e+06,3.172379e+04,1.268656e+04,1.268658e+06,...,1.169484e+02,1.0,8.523126e+02,21.012477,2.728878,14.195251,0.100028,24.466602,1298.375893,NaN
std,1.204984e+00,4.234186e+00,8.873463e+00,1.980054e+00,1.739695e+03,1.534773e+03,1.534770e+05,1.282747e+03,1.534676e+03,1.534673e+05,...,7.374921e+01,0.0,6.198460e+02,59.893115,22.623760,29.501511,2.864423,46.390995,518.465445,NaN
min,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.013500e+04,1.013503e+06,3.007000e+04,1.013500e+04,1.013503e+06,...,7.000000e+00,1.0,2.500000e+01,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,NaN
25%,3.000000e+00,8.000000e+00,8.000000e+00,2.000000e+00,7.000000e+02,1.129200e+04,1.129202e+06,3.061500e+04,1.129200e+04,1.129202e+06,...,6.200000e+01,1.0,3.910000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,833.000000,NaN
50%,3.000000e+00,8.000000e+00,1.600000e+01,4.000000e+00,1.652000e+03,1.288900e+04,1.288903e+06,3.145300e+04,1.288900e+04,1.288903e+06,...,9.800000e+01,1.0,6.790000e+02,2.000000,0.000000,2.000000,0.000000,2.000000,1308.000000,NaN
75%,4.000000e+00,1.100000e+01,2.300000e+01,6.000000e+00,2.895000e+03,1.405700e+04,1.405702e+06,3.246700e+04,1.405700e+04,1.405702e+06,...,1.480000e+02,1.0,1.096000e+03,19.000000,0.000000,18.000000,0.000000,30.000000,1728.000000,NaN
max,4.000000e+00,1.200000e+01,3.100000e+01,7.000000e+00,7.439000e+03,1.621800e+04,1.621801e+06,3.599100e+04,1.621800e+04,1.621801e+06,...,7.230000e+02,1.0,4.983000e+03,1964.000000,1157.000000,1233.000000,437.000000,1484.000000,2400.000000,NaN

In [13]:
#reference a single colum within a dataframe 
flight_file_pd["CARRIER_DELAY"].head()

0     NaN
1    19.0
2     NaN
3     NaN
4     2.0
Name: CARRIER_DELAY, dtype: float64

In [18]:
#reference a single colum within a dataframe 
flight_file_pd["NAS_DELAY"].head()

0     NaN
1     0.0
2     NaN
3     NaN
4    18.0
Name: NAS_DELAY, dtype: float64

In [24]:
#the mean method avergae teh series 
average = flight_file_pd["CARRIER_DELAY"].mean()
average

21.012477469585797

In [26]:
#the sum method adds every entry in teh series 
total = flight_file_pd["CARRIER_DELAY"].sum()
total

7076309.0

In [28]:
count = flight_file_pd["CARRIER_DELAY"].value_counts()
count

0.0       159327
1.0         6509
2.0         6475
3.0         6236
6.0         6229
4.0         6222
7.0         5912
5.0         5903
8.0         5546
9.0         5125
15.0        5092
10.0        4783
16.0        4517
11.0        4410
12.0        4292
17.0        4226
18.0        3829
13.0        3822
19.0        3514
14.0        3505
20.0        3323
21.0        2955
22.0        2780
23.0        2511
24.0        2428
25.0        2237
26.0        2004
27.0        1931
28.0        1769
29.0        1694
           ...
1022.0         1
1025.0         1
1026.0         1
1027.0         1
967.0          1
962.0          1
961.0          1
958.0          1
913.0          1
919.0          1
923.0          1
925.0          1
927.0          1
929.0          1
930.0          1
931.0          1
932.0          1
934.0          1
941.0          1
942.0          1
943.0          1
467.0          1
948.0          1
949.0          1
950.0          1
951.0          1
952.0          1
953.0          1
957.0          1
1272.0         1
Name: CARRIER_DELAY, Length: 1004, dtype: int64

In [44]:
#second csv

In [46]:
import pandas as pd
from sqlalchemy import create_engine

In [47]:
flight_file = "gov2016_flight_delay.csv"
flight_df = pd.read_csv(flight_file)
flight_df.head()

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2016,1,AA,American Airlines Inc.,DFW,"Dallas/Fort Worth, TX: Dallas/Fort Worth Inter...",11956.0,1534.0,507.33,39.83,...,4.72,529.47,201.0,9.0,106950.0,50027.0,2842.0,13913.0,167.0,40001.0
1,2016,1,AA,American Airlines Inc.,DTW,"Detroit, MI: Detroit Metro Wayne County",588.0,98.0,34.71,4.71,...,0.32,38.49,13.0,2.0,5170.0,1754.0,312.0,655.0,16.0,2433.0
2,2016,1,AA,American Airlines Inc.,SEA,"Seattle, WA: Seattle/Tacoma International",607.0,92.0,35.52,5.40,...,0.00,27.52,12.0,2.0,4485.0,1857.0,198.0,715.0,0.0,1715.0
3,2016,1,AA,American Airlines Inc.,JFK,"New York, NY: John F. Kennedy International",1595.0,335.0,117.00,10.26,...,0.83,89.25,137.0,6.0,23698.0,9681.0,1592.0,4371.0,18.0,8036.0
4,2016,1,AA,American Airlines Inc.,SJC,"San Jose, CA: Norman Y. Mineta San Jose Intern...",327.0,59.0,23.67,1.47,...,0.06,19.29,0.0,0.0,2276.0,985.0,94.0,373.0,5.0,819.0

In [52]:
#look for missing values 
flight_df.count()

year                   12217
 month                 12217
carrier                12217
carrier_name           12217
airport                12217
airport_name           12217
arr_flights            12198
arr_del15              12195
carrier_ct             12198
 weather_ct            12198
nas_ct                 12198
security_ct            12198
late_aircraft_ct       12198
arr_cancelled          12198
arr_diverted           12198
 arr_delay             12198
 carrier_delay         12198
weather_delay          12198
nas_delay              12198
security_delay         12198
late_aircraft_delay    12198
dtype: int64

In [55]:
#remove the rows with missing data
clean_flight_df = flight_df.dropna(how="any")
clean_flight_df.count()

year                   12195
 month                 12195
carrier                12195
carrier_name           12195
airport                12195
airport_name           12195
arr_flights            12195
arr_del15              12195
carrier_ct             12195
 weather_ct            12195
nas_ct                 12195
security_ct            12195
late_aircraft_ct       12195
arr_cancelled          12195
arr_diverted           12195
 arr_delay             12195
 carrier_delay         12195
weather_delay          12195
nas_delay              12195
security_delay         12195
late_aircraft_delay    12195
dtype: int64

In [57]:
#filter the data so that only those sighting in the US are in a data frame
AA_flight_df = clean_flight_df.loc[clean_flight_df["carrier"] =="AA", :]
AA_flight_df

,year,month,carrier,carrier_name,airport,airport_name,arr_flights,arr_del15,carrier_ct,weather_ct,...,security_ct,late_aircraft_ct,arr_cancelled,arr_diverted,arr_delay,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay
0,2016,1,AA,American Airlines Inc.,DFW,"Dallas/Fort Worth, TX: Dallas/Fort Worth Inter...",11956.0,1534.0,507.33,39.83,...,4.72,529.47,201.0,9.0,106950.0,50027.0,2842.0,13913.0,167.0,40001.0
1,2016,1,AA,American Airlines Inc.,DTW,"Detroit, MI: Detroit Metro Wayne County",588.0,98.0,34.71,4.71,...,0.32,38.49,13.0,2.0,5170.0,1754.0,312.0,655.0,16.0,2433.0
2,2016,1,AA,American Airlines Inc.,SEA,"Seattle, WA: Seattle/Tacoma International",607.0,92.0,35.52,5.40,...,0.00,27.52,12.0,2.0,4485.0,1857.0,198.0,715.0,0.0,1715.0
3,2016,1,AA,American Airlines Inc.,JFK,"New York, NY: John F. Kennedy International",1595.0,335.0,117.00,10.26,...,0.83,89.25,137.0,6.0,23698.0,9681.0,1592.0,4371.0,18.0,8036.0
4,2016,1,AA,American Airlines Inc.,SJC,"San Jose, CA: Norman Y. Mineta San Jose Intern...",327.0,59.0,23.67,1.47,...,0.06,19.29,0.0,0.0,2276.0,985.0,94.0,373.0,5.0,819.0
5,2016,1,AA,American Airlines Inc.,ORD,"Chicago, IL: Chicago O'Hare International",4664.0,607.0,198.83,16.75,...,0.99,155.81,98.0,2.0,33906.0,12889.0,1357.0,9182.0,242.0,10236.0
6,2016,1,AA,American Airlines Inc.,PHX,"Phoenix, AZ: Phoenix Sky Harbor International",4993.0,617.0,225.25,10.24,...,0.12,154.31,86.0,3.0,31060.0,14884.0,1003.0,6267.0,5.0,8901.0
7,2016,1,AA,American Airlines Inc.,STL,"St. Louis, MO: St Louis Lambert International",661.0,109.0,50.08,7.39,...,0.00,35.61,8.0,1.0,6142.0,2707.0,394.0,490.0,0.0,2551.0
8,2016,1,AA,American Airlines Inc.,LAX,"Los Angeles, CA: Los Angeles International",3192.0,611.0,231.06,17.86,...,1.29,168.84,74.0,2.0,37701.0,17618.0,1351.0,6832.0,36.0,11864.0
9,2016,1,AA,American Airlines Inc.,MCO,"Orlando, FL: Orlando International",1639.0,409.0,143.71,13.08,...,1.09,92.72,55.0,2.0,19038.0,8099.0,676.0,4865.0,35.0,5363.0
10,2016,1,AA,American Airlines Inc.,DEN,"Denver, CO: Denver International",818.0,139.0,60.69,3.57,...,0.18,46.26,14.0,0.0,7423.0,3531.0,213.0,816.0,3.0,2860.0
11,2016,1,AA,American Airlines Inc.,MIA,"Miami, FL: Miami International",4628.0,1222.0,335.41,31.03,...,7.77,245.41,135.0,42.0,74959.0,28660.0,3960.0,21886.0,307.0,20146.0
12,2016,1,AA,American Airlines Inc.,KOA,"Kona, HI: Ellison Onizuka Kona International a...",70.0,30.0,10.41,1.00,...,0.00,1.78,0.0,0.0,1603.0,809.0,35.0,537.0,0.0,222.0
13,2016,1,AA,American Airlines Inc.,IAH,"Houston, TX: George Bush Intercontinental/Houston",662.0,120.0,50.15,3.17,...,0.63,30.16,12.0,2.0,5967.0,2566.0,126.0,1290.0,82.0,1903.0
14,2016,1,AA,American Airlines Inc.,AUS,"Austin, TX: Austin - Bergstrom International",751.0,90.0,41.91,2.40,...,0.00,33.38,10.0,1.0,4800.0,2289.0,140.0,479.0,0.0,1892.0
15,2016,1,AA,American Airlines Inc.,LAS,"Las Vegas, NV: McCarran International",1293.0,221.0,70.68,5.31,...,0.05,70.71,31.0,3.0,13526.0,4263.0,434.0,4137.0,1.0,4691.0
16,2016,1,AA,American Airlines Inc.,SLC,"Salt Lake City, UT: Salt Lake City International",408.0,60.0,23.04,1.21,...,0.00,24.08,4.0,1.0,2783.0,1181.0,73.0,339.0,0.0,1190.0
17,2016,1,AA,American Airlines Inc.,TUS,"Tucson, AZ: Tucson International",271.0,24.0,10.82,0.43,...,0.00,10.49,1.0,1.0,1141.0,457.0,23.0,100.0,0.0,561.0
18,2016,1,AA,American Airlines Inc.,STT,"Charlotte Amalie, VI: Cyril E King",168.0,33.0,11.69,1.76,...,0.00,3.76,7.0,0.0,2548.0,1459.0,154.0,448.0,0.0,487.0
19,2016,1,AA,American Airlines Inc.,BOS,"Boston, MA: Logan International",2236.0,336.0,126.44,16.08,...,0.00,97.45,97.0,1.0,16876.0,7490.0,821.0,3235.0,0.0,5330.0
20,2016,1,AA,American Airlines Inc.,FLL,"Fort Lauderdale, FL: Fort Lauderdale-Hollywood...",819.0,157.0,54.01,4.72,...,0.00,38.36,32.0,2.0,7056.0,2956.0,270.0,1870.0,0.0,1960.0
21,2016,1,AA,American Airlines Inc.,SFO,"San Francisco, CA: San Francisco International",1270.0,376.0,73.87,10.43,...,0.80,52.67,34.0,0.0,21952.0,4180.0,877.0,13054.0,49.0,3792.0
22,2016,1,AA,American Airlines Inc.,OGG,"Kahului, HI: Kahului Airport",138.0,71.0,20.68,0.00,...,0.39,2.96,0.0,1.0,3780.0,1639.0,0.0,1746.0,20.0,375.0
23,2016,1,AA,American Airlines Inc.,TPA,"Tampa, FL: Tampa International",1028.0,208.0,83.25,4.82,...,0.94,57.12,34.0,1.0,10652.0,4904.0,268.0,1897.0,16.0,3567.0
24,2016,1,AA,American Airlines Inc.,SNA,"Santa Ana, CA: John Wayne Airport-Orange County",467.0,51.0,22.42,3.20,...,0.00,16.92,1.0,0.0,1763.0,735.0,94.0,203.0,0.0,731.0
25,2016,1,AA,American Airlines Inc.,OKC,"Oklahoma City, OK: Will Rogers World",153.0,15.0,7.09,0.00,...,0.00,7.52,0.0,0.0,571.0,251.0,0.0,17.0,0.0,303.0
26,2016,1,AA,American Airlines Inc.,HNL,"Honolulu, HI: Daniel K Inouye International",221.0,108.0,38.45,1.02,...,0.74,12.70,0.0,1.0,6328.0,2913.0,59.0,2002.0,21.0,1333.0
27,2016,1,AA,American Airlines Inc.,PHL,"Philadelphia, PA: Philadelphia International",3508.0,495.0,186.34,13.97,...,0.18,161.96,225.0,2.0,30141.0,12169.0,2339.0,4686.0,7.0,10940.0
28,2016,1,AA,American Airlines Inc.,LGA,"New York, NY: LaGuardia",2136.0,430.0,126.80,16.41,...,0.13,122.87,176.0,3.0,21966.0,6787.0,1367.0,6893.0,2.0,6917.0
29,2016,1,AA,American Airlines Inc.,RDU,"Raleigh/Durham, NC: Raleigh-Durham International",631.0,108.0,59.52,2.89,...,0.00,27.54,37.0,0.0,5710.0,2861.0,254.0,562.0,0.0,2033.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11256,2016,12,AA,American Airlines Inc.,BWI,"Baltimore, MD: Baltimore/Washington Internatio...",479.0,72.0,27.72,0.00,...,0.00,28.87,2.0,0.0,3598.0,1305.0,0.0,376.0,0.0,1917.0
11257,2016,12,AA,American Airlines Inc.,PVD,"Providence, RI: Theodore Francis Green State",205.0,23.0,6.12,0.00,...,0.00,11.94,2.0,0.0,1339.0,353.0,0.0,155.0,0.0,831.0
11258,2016,12,AA,American Airlines Inc.,PWM,"Portland, ME: Portland International Jetport",60.0,8.0,3.65,0.00,...,0.00,2.13,1.0,0.0,543.0,258.0,0.0,88.0,0.0,197.0
11259,2016,12,AA,American Airlines Inc.,IAD,"Washington, DC: Washington Dulles International",227.0,38.0,19.90,0.00,...,0.00,10.95,2.0,0.0,1767.0,822.0,0.0,253.0,0.0,692.0
11260,2016,12,AA,American Airlines Inc.,BUF,"Buffalo, NY: Buffalo Niagara International",95.0,19.0,8.86,0.00,...,0.00,3.54,1.0,1.0,696.0,339.0,0.0,210.0,0.0,147.0
11261,2016,12,AA,American Airlines Inc.,ROC,"Rochester, NY: Greater Rochester International",56.0,15.0,5.93,0.00,...,0.00,4.25,2.0,0.0,548.0,269.0,0.0,122.0,0.0,157.0
11262,2016,12,AA,American Airlines Inc.,SYR,"Syracuse, NY: Syracuse Hancock International",53.0,12.0,7.20,0.00,...,0.00,2.39,0.0,1.0,486.0,334.0,0.0,76.0,0.0,76.0
11263,2016,12,AA,American Airlines Inc.,OAK,"Oakland, CA: Metropolitan Oakland International",87.0,23.0,11.53,0.00,...,0.00,6.59,0.0,0.0,805.0,394.0,0.0,130.0,0.0,281.0
11264,2016,12,AA,American Airlines Inc.,RIC,"Richmond, VA: Richmond International",184.0,26.0,7.00,0.21,...,0.00,11.57,1.0,0.0,1002.0,207.0,12.0,195.0,0.0,588.0
11265,2016,12,AA,American Airlines Inc.,ALB,"Albany, NY: Albany International",81.0,7.0,4.08,0.00,...,0.00,0.16,0.0,0.0,243.0,166.0,0.0,74.0,0.0,3.0
11266,2016,12,AA,American Airlines Inc.,ILM,"Wilmington, NC: Wilmington International",79.0,11.0,4.94,0.00,...,0.00,3.73,0.0,0.0,421.0,172.0,0.0,76.0,0.0,173.0
11267,2016,12,AA,American Airlines Inc.,MDT,"Harrisburg, PA: Harrisburg International",14.0,3.0,0.73,0.00,...,0.00,2.02,0.0,0.0,159.0,41.0,0.0,6.0,0.0,112.0
11268,2016,12,AA,American Airlines Inc.,CHS,"Charleston, SC: Charleston AFB/International",25.0,4.0,1.28,0.00,...,0.00,1.37,0.0,0.0,137.0,36.0,0.0,38.0,0.0,63.0
11269,2016,12,AA,American Airlines Inc.,DAY,"Dayton, OH: James M Cox/Dayton International",59.0,12.0,4.49,0.00,...,0.00,7.51,1.0,0.0,605.0,191.0,0.0,0.0,0.0,414.0
11270,2016,12,AA,American Airlines Inc.,LBB,"Lubbock, TX: Lubbock Preston Smith International",28.0,6.0,2.69,0.00,...,0.00,2.30,1.0,0.0,241.0,137.0,0.0,26.0,0.0,78.0
11271,2016,12,AA,American Airlines Inc.,EGE,"Eagle, CO: Eagle County Regional",141.0,50.0,16.93,1.60,...,0.00,7.26,2.0,2.0,5932.0,1967.0,1847.0,1075.0,0.0,1043.0
11272,2016,12,AA,American Airlines Inc.,SDF,"Louisville, KY: Louisville International-Stand...",26.0,4.0,2.07,0.00,...,0.00,1.43,0.0,0.0,147.0,73.0,0.0,9.0,0.0,65.0
11273,2016,12,AA,American Airlines Inc.,RNO,"Reno, NV: Reno/Tahoe International",114.0,27.0,9.82,0.42,...,0.87,8.06,0.0,1.0,1329.0,487.0,53.0,230.0,13.0,546.0
11274,2016,12,AA,American Airlines Inc.,ABQ,"Albuquerque, NM: Albuquerque International Sun...",114.0,30.0,11.48,0.00,...,0.00,15.41,1.0,0.0,1942.0,635.0,0.0,107.0,0.0,1200.0
11275,2016,12,AA,American Airlines Inc.,MFE,"Mission/McAllen/Edinburg, TX: McAllen Miller I...",50.0,10.0,5.31,0.00,...,0.00,1.07,1.0,0.0,456.0,301.0,0.0,85.0,0.0,70.0
11276,2016,12,AA,American Airlines Inc.,STX,"Christiansted, VI: Henry E. Rohlsen",59.0,10.0,4.33,0.98,...,0.11,3.37,0.0,0.0,536.0,240.0,97.0,53.0,2.0,144.0
11277,2016,12,AA,American Airlines Inc.,ELP,"El Paso, TX: El Paso International",107.0,29.0,11.72,0.00,...,0.00,12.37,0.0,0.0,1555.0,407.0,0.0,138.0,0.0,1010.0
11278,2016,12,AA,American Airlines Inc.,PSP,"Palm Springs, CA: Palm Springs International",106.0,28.0,10.26,0.00,...,0.00,7.20,1.0,0.0,1780.0,900.0,0.0,367.0,0.0,513.0
11279,2016,12,AA,American Airlines Inc.,AMA,"Amarillo, TX: Rick Husband Amarillo International",14.0,2.0,0.00,0.00,...,0.00,1.00,0.0,0.0,43.0,0.0,0.0,21.0,0.0,22.0
11280,2016,12,AA,American Airlines Inc.,ICT,"Wichita, KS: Wichita Dwight D Eisenhower National",13.0,1.0,0.47,0.00,...,0.00,0.53,0.0,0.0,102.0,48.0,0.0,0.0,0.0,54.0
11281,2016,12,AA,American Airlines Inc.,JAC,"Jackson, WY: Jackson Hole",51.0,21.0,4.34,1.07,...,0.00,6.57,1.0,2.0,2734.0,305.0,643.0,932.0,0.0,854.0
11282,2016,12,AA,American Airlines Inc.,CRP,"Corpus Christi, TX: Corpus Christi International",11.0,2.0,1.32,0.00,...,0.00,0.68,0.0,0.0,119.0,71.0,0.0,0.0,0.0,48.0
11283,2016,12,AA,American Airlines Inc.,HDN,"Hayden, CO: Yampa Valley",36.0,16.0,2.88,0.00,...,0.00,2.82,0.0,0.0,794.0,156.0,0.0,298.0,0.0,340.0
11284,2016,12,AA,American Airlines Inc.,GUC,"Gunnison, CO: Gunnison-Crested Butte Regional",23.0,8.0,2.68,0.65,...,0.00,1.36,0.0,1.0,342.0,96.0,70.0,122.0,0.0,54.0
11285,2016,12,AA,American Airlines Inc.,MTJ,"Montrose/Delta, CO: Montrose Regional",20.0,5.0,1.88,0.00,...,0.00,0.52,0.0,0.0,292.0,121.0,0.0,71.0,0.0,100.0

In [59]:
AA_counts = AA_flight_df ["weather_delay"].value_counts()
AA_counts

0.0       311
18.0        6
49.0        5
20.0        5
65.0        5
38.0        5
92.0        5
12.0        5
195.0       5
4.0         5
14.0        5
35.0        5
114.0       5
58.0        4
27.0        4
10.0        4
45.0        4
5.0         4
91.0        4
50.0        4
15.0        4
44.0        4
53.0        4
55.0        4
64.0        4
94.0        4
93.0        4
32.0        4
140.0       4
120.0       4
         ...
792.0       1
237.0       1
370.0       1
138.0       1
428.0       1
153.0       1
105.0       1
241.0       1
146.0       1
1168.0      1
209.0       1
552.0       1
298.0       1
222.0       1
380.0       1
744.0       1
123.0       1
406.0       1
536.0       1
420.0       1
2397.0      1
388.0       1
137.0       1
178.0       1
680.0       1
984.0       1
121.0       1
202.0       1
1840.0      1
312.0       1
Name: weather_delay, Length: 536, dtype: int64

In [60]:
#convert the count to series into dataframe 
AA_flight_counts_df = pd.DataFrame(AA_counts)
AA_flight_counts_df.head()

      weather_delay
0.0             311
18.0              6
49.0              5
20.0              5
65.0              5